/pickup_pose_cmd_node:
  ros__parameters:
    ros_node:
      subs:
        gazebo_poses: "/gazebo/pose"
        pickup_pose_cmd: "/debug/pickup/cmd_pose" # "/debug/pickup/cmd_pose"
      pubs:
        pickup_pose_cmd: /model/pickup/cmd_pose # "/drone/planner/goal" # "/model/pickup/cmd_pose"
      thread_freq: 50.0
      en_input: false
      model_idx: 3 # 3
      path_pub_period: 2.5 # [s]
      path_file: "install/drone_simulation/share/drone_simulation/sim_files/path07.txt"
